#' @title View the benchmark tasks
#'
#' @description
#' Loads the benchmark tasks to be run on an OMOP-CDM.
#'
#' @param tasks Define which tasks should be loaded. Choice of "all" to load all tasks or a numeric vector to define which.
#'
#' @export
viewBenchmarkTasks <- function(tasks = "all") {
  viewTasks <- checkmate::makeAssertCollection()

  if (is.character(tasks)) {
    checkmate::assert(checkmate::checkCharacter(tasks, null.ok = FALSE),
      checkmate::checkChoice(tasks, choices = "all", null.ok = FALSE),
      combine = "and",
      add = viewTasks
    )
  } else if (is.numeric(tasks)) {
    checkmate::assert(checkmate::checkIntegerish(tasks, null.ok = FALSE, lower = 1, any.missing = FALSE, all.missing = FALSE),
      add = viewTasks
    )
  }

  checkmate::reportAssertions(viewTasks)

  if (is.null(tasks)) {
    stop("Argument 'tasks' is NULL. Nothing to view.")
  } else if (is.character(tasks)) {
    problemList <- read.csv(system.file(package = "PLPBenchmarks", "extdata", "ProblemSpecification.csv")) %>%
      dplyr::as_tibble()
  } else if (is.numeric(tasks)) {
    problemList <- read.csv(system.file(package = "PLPBenchmarks", "extdata", "ProblemSpecification.csv")) %>%
      dplyr::as_tibble() %>%
      dplyr::filter(PId %in% tasks)
  }

  return(problemList)
}


#' @title Loads the model design list
#'
#' @description
#' Loads the models design list.
#'
#' @details
#' A model design is an object of class `modelDesign` as generated by `PatientLevelPrediction::createModelDesign()`.
#'
#'
#' @param designs Define which designs should be loaded. Choice of "all" to load all tasks or a numeric vector to define which.
#'
#' @export
loadModelDesigns <- function(designs = "all") {
  loadDesigns <- checkmate::makeAssertCollection()

  if (is.character(designs)) {
    checkmate::assert(checkmate::checkCharacter(designs, null.ok = FALSE),
      checkmate::checkChoice(designs, choices = "all", null.ok = FALSE),
      combine = "and",
      add = loadDesigns
    )
  }
  if (is.numeric(designs)) {
    checkmate::assert(checkmate::checkIntegerish(designs, null.ok = FALSE, lower = 1, any.missing = FALSE, all.missing = FALSE),
      add = loadDesigns
    )
  }
  if (is.data.frame(designs)) {
    checkmate::assert(checkmate::checkDataFrame(designs, min.cols = 1, min.rows = 1, col.names = "named"),
      checkmate::checkSubset("PId", choices = names(designs), empty.ok = FALSE),
      combine = "and",
      add = loadDesigns
    )
  }

  checkmate::reportAssertions(loadDesigns)

  if (is.null(designs)) {
    stop("Argument 'tasks' is NULL. Nothing to load.")
  } else if (is.character(designs)) {
    designList <- readRDS(system.file(package = "PLPBenchmarks", "extdata", "BenchmarkModelDesignList.Rds"))
  } else if (is.numeric(designs)) {
    designList <- readRDS(system.file(package = "PLPBenchmarks", "extdata", "BenchmarkModelDesignList.Rds"))
    if (max(designs) < length(designList)){
      designList <- designList[c(designs)]
    } else if (is.double(designs) & max(designs) > length(designList)) {
      designList <- list(NULL)
    } else if (is.vector(designs) & max(designs) > length(designList)) {
      designList
    }
  } else if (is.data.frame(designs)) {
    designList <- readRDS(system.file(package = "PLPBenchmarks", "extdata", "BenchmarkModelDesignList.Rds"))
    designList <- designList[c(designs$PId)]
  }

  return(designList)
}
